#define CUDA_RESULTS \
	RES(CUDA_SUCCESS, 0) \
	RES(CUDA_ERROR_INVALID_VALUE, 1) \
	RES(CUDA_ERROR_OUT_OF_MEMORY, 2) \
	RES(CUDA_ERROR_NOT_INITIALIZED, 3) \
	RES(CUDA_ERROR_DEINITIALIZED, 4) \
	RES(CUDA_ERROR_PROFILER_DISABLED, 5) \
	RES(CUDA_ERROR_PROFILER_NOT_INITIALIZED, 6) \
	RES(CUDA_ERROR_PROFILER_ALREADY_STARTED, 7) \
	RES(CUDA_ERROR_PROFILER_ALREADY_STOPPED, 8) \
	RES(CUDA_ERROR_NO_DEVICE, 100) \
	RES(CUDA_ERROR_INVALID_DEVICE, 101) \
	RES(CUDA_ERROR_INVALID_IMAGE, 200) \
	RES(CUDA_ERROR_INVALID_CONTEXT, 201) \
	RES(CUDA_ERROR_CONTEXT_ALREADY_CURRENT, 202) \
	RES(CUDA_ERROR_MAP_FAILED, 205) \
	RES(CUDA_ERROR_UNMAP_FAILED, 206) \
	RES(CUDA_ERROR_ARRAY_IS_MAPPED, 207) \
	RES(CUDA_ERROR_ALREADY_MAPPED, 208) \
	RES(CUDA_ERROR_NO_BINARY_FOR_GPU, 209) \
	RES(CUDA_ERROR_ALREADY_ACQUIRED, 210) \
	RES(CUDA_ERROR_NOT_MAPPED, 211) \
	RES(CUDA_ERROR_NOT_MAPPED_AS_ARRAY, 212) \
	RES(CUDA_ERROR_NOT_MAPPED_AS_POINTER, 213) \
	RES(CUDA_ERROR_ECC_UNCORRECTABLE, 214) \
	RES(CUDA_ERROR_UNSUPPORTED_LIMIT, 215) \
	RES(CUDA_ERROR_CONTEXT_ALREADY_IN_USE, 216) \
	RES(CUDA_ERROR_PEER_ACCESS_UNSUPPORTED, 217) \
	RES(CUDA_ERROR_INVALID_PTX, 218) \
	RES(CUDA_ERROR_INVALID_SOURCE, 300) \
	RES(CUDA_ERROR_FILE_NOT_FOUND, 301) \
	RES(CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND, 302) \
	RES(CUDA_ERROR_SHARED_OBJECT_INIT_FAILED, 303) \
	RES(CUDA_ERROR_OPERATING_SYSTEM, 304) \
	RES(CUDA_ERROR_INVALID_HANDLE, 400) \
	RES(CUDA_ERROR_NOT_FOUND, 500) \
	RES(CUDA_ERROR_NOT_READY, 600) \
	RES(CUDA_ERROR_ILLEGAL_ADDRESS, 700) \
	RES(CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES, 701) \
	RES(CUDA_ERROR_LAUNCH_TIMEOUT, 702) \
	RES(CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING, 703) \
	RES(CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED, 704) \
	RES(CUDA_ERROR_PEER_ACCESS_NOT_ENABLED, 705) \
	RES(CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE, 708) \
	RES(CUDA_ERROR_CONTEXT_IS_DESTROYED, 709) \
	RES(CUDA_ERROR_ASSERT, 710) \
	RES(CUDA_ERROR_TOO_MANY_PEERS, 711) \
	RES(CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED, 712) \
	RES(CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED, 713) \
	RES(CUDA_ERROR_HARDWARE_STACK_ERROR, 714) \
	RES(CUDA_ERROR_ILLEGAL_INSTRUCTION, 715) \
	RES(CUDA_ERROR_MISALIGNED_ADDRESS, 716) \
	RES(CUDA_ERROR_INVALID_ADDRESS_SPACE, 717) \
	RES(CUDA_ERROR_INVALID_PC, 718) \
	RES(CUDA_ERROR_LAUNCH_FAILED, 719) \
	RES(CUDA_ERROR_NOT_PERMITTED, 800) \
	RES(CUDA_ERROR_NOT_SUPPORTED, 801) \
	RES(CUDA_ERROR_UNKNOWN, 999)


#define RES(ENUM, VALUE) [VALUE] = #ENUM,
static const char *CUDA_RESULT_STRING[] = {
	CUDA_RESULTS
};
#undef RES

#define CUDA_RESULT_STRING_ARR_SIZE \
	(int) (sizeof(CUDA_RESULT_STRING)/sizeof(CUDA_RESULT_STRING[0]))
